//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lí_Account_Facebook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_TKFB
    {
        public int STT { get; set; }
        public string Tài_khoản { get; set; }
        public string Mật_khẩu { get; set; }
        public string Tên_người_dùng { get; set; }
        public Nullable<int> Số_điện_thoại { get; set; }
        public string Email { get; set; }
    }
}
